[2022-07-31 15:04:46,655] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-07-30T13:37:00+00:00 [queued]>
[2022-07-31 15:04:46,673] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-07-30T13:37:00+00:00 [queued]>
[2022-07-31 15:04:46,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:04:46,673] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-07-31 15:04:46,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-31 15:04:46,716] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-07-30 13:37:00+00:00
[2022-07-31 15:04:46,721] {standard_task_runner.py:52} INFO - Started process 839864 to run task
[2022-07-31 15:04:46,733] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'scheduled__2022-07-30T13:37:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmps6g8f_ba', '--error-file', '/tmp/tmpk6l__icd']
[2022-07-31 15:04:46,734] {standard_task_runner.py:80} INFO - Job 121: Subtask nse_files_move
[2022-07-31 15:04:46,811] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-07-30T13:37:00+00:00 [running]> on host osboxes
[2022-07-31 15:04:47,019] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-07-30T13:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-30T13:37:00+00:00
[2022-07-31 15:04:47,061] {logging_mixin.py:115} INFO - 2022-07-31
[2022-07-31 15:04:47,071] {logging_mixin.py:115} INFO - directory already available
[2022-07-31 15:04:47,071] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-07-31 target file location
[2022-07-31 15:04:47,072] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-07-31/cm29JUL2022bhav.csv.zip' already exists
[2022-07-31 15:04:47,073] {python.py:173} INFO - Done. Returned value was: None
[2022-07-31 15:04:47,115] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220730T133700, start_date=20220731T190446, end_date=20220731T190447
[2022-07-31 15:04:47,185] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-31 15:04:47,262] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
