[2022-09-05 10:49:05,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-09-04T13:37:00+00:00 [queued]>
[2022-09-05 10:49:05,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-09-04T13:37:00+00:00 [queued]>
[2022-09-05 10:49:05,773] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:49:05,773] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-09-05 10:49:05,773] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:49:05,811] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-09-04 13:37:00+00:00
[2022-09-05 10:49:05,814] {standard_task_runner.py:52} INFO - Started process 65624 to run task
[2022-09-05 10:49:05,822] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'scheduled__2022-09-04T13:37:00+00:00', '--job-id', '485', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmp1yc3uulo', '--error-file', '/tmp/tmpp347lht3']
[2022-09-05 10:49:05,823] {standard_task_runner.py:80} INFO - Job 485: Subtask nse_files_move
[2022-09-05 10:49:06,177] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-09-04T13:37:00+00:00 [running]> on host osboxes
[2022-09-05 10:49:07,001] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T13:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T13:37:00+00:00
[2022-09-05 10:49:07,002] {logging_mixin.py:115} INFO - 2022-09-05
[2022-09-05 10:49:07,005] {logging_mixin.py:115} INFO - directory already available
[2022-09-05 10:49:07,005] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-09-05 target file location
[2022-09-05 10:49:07,027] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm02SEP2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-09-05/cm02SEP2022bhav.csv.zip' already exists
[2022-09-05 10:49:07,040] {python.py:173} INFO - Done. Returned value was: None
[2022-09-05 10:49:07,103] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220904T133700, start_date=20220905T144905, end_date=20220905T144907
[2022-09-05 10:49:07,262] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 10:49:07,683] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
