[2022-08-28 11:17:47,691] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-08-25T13:37:00+00:00 [queued]>
[2022-08-28 11:17:47,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-08-25T13:37:00+00:00 [queued]>
[2022-08-28 11:17:47,725] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 11:17:47,726] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-08-28 11:17:47,726] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 11:17:47,787] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-08-25 13:37:00+00:00
[2022-08-28 11:17:47,791] {standard_task_runner.py:52} INFO - Started process 22957 to run task
[2022-08-28 11:17:47,795] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'scheduled__2022-08-25T13:37:00+00:00', '--job-id', '409', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmp57oqy088', '--error-file', '/tmp/tmpufh9zu3g']
[2022-08-28 11:17:47,813] {standard_task_runner.py:80} INFO - Job 409: Subtask nse_files_move
[2022-08-28 11:17:47,967] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move scheduled__2022-08-25T13:37:00+00:00 [running]> on host osboxes
[2022-08-28 11:17:48,056] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-08-25T13:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-25T13:37:00+00:00
[2022-08-28 11:17:48,057] {logging_mixin.py:115} INFO - 2022-08-28
[2022-08-28 11:17:48,057] {logging_mixin.py:115} INFO - directory already available
[2022-08-28 11:17:48,057] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-08-28 target file location
[2022-08-28 11:17:48,058] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm12AUG2022bhav.csv 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-08-28/cm12AUG2022bhav.csv' already exists
[2022-08-28 11:17:48,060] {python.py:173} INFO - Done. Returned value was: None
[2022-08-28 11:17:48,079] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220825T133700, start_date=20220828T151747, end_date=20220828T151748
[2022-08-28 11:17:48,144] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 11:17:48,201] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
