[2022-08-11 22:46:46,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-08-12T02:46:13.868910+00:00 [queued]>
[2022-08-11 22:46:46,878] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-08-12T02:46:13.868910+00:00 [queued]>
[2022-08-11 22:46:46,878] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:46:46,878] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-11 22:46:46,879] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:46:46,980] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): nse_files_move> on 2022-08-12 02:46:13.868910+00:00
[2022-08-11 22:46:47,008] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'nse_files_move', 'manual__2022-08-12T02:46:13.868910+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmpag7h4sz6', '--error-file', '/tmp/tmp_qdi20h8']
[2022-08-11 22:46:47,025] {standard_task_runner.py:52} INFO - Started process 31070 to run task
[2022-08-11 22:46:47,072] {standard_task_runner.py:80} INFO - Job 261: Subtask nse_files_move
[2022-08-11 22:46:47,399] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.nse_files_move manual__2022-08-12T02:46:13.868910+00:00 [running]> on host osboxes
[2022-08-11 22:46:47,664] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=nse_files_move
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T02:46:13.868910+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-12T02:46:13.868910+00:00
[2022-08-11 22:46:47,665] {logging_mixin.py:115} INFO - 2022-08-11
[2022-08-11 22:46:47,665] {logging_mixin.py:115} INFO - directory already available
[2022-08-11 22:46:47,665] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/archives_files/2022-08-11 target file location
[2022-08-11 22:46:47,680] {logging_mixin.py:115} INFO - /home/osboxes/Desktop/Files/cm29JUL2022bhav.csv.zip 
 error identified Destination path '/home/osboxes/Desktop/archives_files/2022-08-11/cm29JUL2022bhav.csv.zip' already exists
[2022-08-11 22:46:47,681] {python.py:173} INFO - Done. Returned value was: None
[2022-08-11 22:46:47,701] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=nse_files_move, execution_date=20220812T024613, start_date=20220812T024646, end_date=20220812T024647
[2022-08-11 22:46:47,773] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 22:46:48,187] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
