[2022-08-09 11:14:42,258] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Stockdim_update.stg_2_tgt_merge_sd manual__2022-08-09T06:36:46.184026+00:00 [queued]>
[2022-08-09 11:14:42,264] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Stockdim_update.stg_2_tgt_merge_sd manual__2022-08-09T06:36:46.184026+00:00 [queued]>
[2022-08-09 11:14:42,264] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 11:14:42,264] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-09 11:14:42,264] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-09 11:14:42,303] {taskinstance.py:1377} INFO - Executing <Task(SnowflakeOperator): stg_2_tgt_merge_sd> on 2022-08-09 06:36:46.184026+00:00
[2022-08-09 11:14:42,306] {standard_task_runner.py:52} INFO - Started process 182333 to run task
[2022-08-09 11:14:42,317] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Stockdim_update', 'stg_2_tgt_merge_sd', 'manual__2022-08-09T06:36:46.184026+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/stock_scd2.py', '--cfg-path', '/tmp/tmpljfqa9l4', '--error-file', '/tmp/tmp6967cksb']
[2022-08-09 11:14:42,317] {standard_task_runner.py:80} INFO - Job 216: Subtask stg_2_tgt_merge_sd
[2022-08-09 11:14:42,398] {task_command.py:369} INFO - Running <TaskInstance: Stockdim_update.stg_2_tgt_merge_sd manual__2022-08-09T06:36:46.184026+00:00 [running]> on host osboxes
[2022-08-09 11:14:42,542] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=NSEstock
AIRFLOW_CTX_DAG_ID=Stockdim_update
AIRFLOW_CTX_TASK_ID=stg_2_tgt_merge_sd
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T06:36:46.184026+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-09T06:36:46.184026+00:00
[2022-08-09 11:14:42,542] {snowflake.py:118} INFO - Executing:  MERGE into EDW_DEV.EDW.STOCK_DIM sd
using EDW_DEV.EDW.STOCK_DIM_STRM sdstr on sd.ISIN_CODE = sdstr.ISIN_CODE
when not matched and sdstr.METADATA$ACTION ='INSERT' and sdstr.METADATA$ISUPDATE = FALSE 
then
insert (sd.COMPANY_NAME,sd.INDUSTRY,sd.SYMBOL,sd.SERIES,sd.ISIN_code,sd.INDEX_NAME)  
values (sdstr.COMPANY_NAME,sdstr.INDUSTRY,sdstr.SYMBOL,sdstr.SERIES,sdstr.ISIN_code,case sdstr.INDEX_NAME like '%200%' then 'Nifty101-200 else 'Nifty201-onwards' end)
[2022-08-09 11:14:42,574] {base.py:68} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2022-08-09 11:14:42,577] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.10, Platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[2022-08-09 11:14:42,579] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-09 11:14:42,579] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-08-09 11:14:43,817] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-09 11:14:43,958] {cursor.py:734} INFO - query execution done
[2022-08-09 11:14:43,959] {snowflake.py:328} INFO - Running statement: MERGE into EDW_DEV.EDW.STOCK_DIM sd
using EDW_DEV.EDW.STOCK_DIM_STRM sdstr on sd.ISIN_CODE = sdstr.ISIN_CODE
when not matched and sdstr.METADATA$ACTION ='INSERT' and sdstr.METADATA$ISUPDATE = FALSE 
then
insert (sd.COMPANY_NAME,sd.INDUSTRY,sd.SYMBOL,sd.SERIES,sd.ISIN_code,sd.INDEX_NAME)  
values (sdstr.COMPANY_NAME,sdstr.INDUSTRY,sdstr.SYMBOL,sdstr.SERIES,sdstr.ISIN_code,case sdstr.INDEX_NAME like '%200%' then 'Nifty101-200 else 'Nifty201-onwards' end), parameters: None
[2022-08-09 11:14:43,959] {cursor.py:710} INFO - query: [MERGE into EDW_DEV.EDW.STOCK_DIM sd using EDW_DEV.EDW.STOCK_DIM_STRM sdstr on sd...]
[2022-08-09 11:14:44,123] {cursor.py:734} INFO - query execution done
[2022-08-09 11:14:44,125] {connection.py:507} INFO - closed
[2022-08-09 11:14:44,206] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-08-09 11:14:44,277] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/osboxes/.local/lib/python3.8/site-packages/airflow/providers/snowflake/operators/snowflake.py", line 120, in execute
    execution_info = hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/osboxes/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 332, in run
    cur.execute(sql_statement)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 799, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 273, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 328, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/osboxes/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 207, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01a62cb2-0501-b543-006e-0a830001f12a: SQL compilation error:
syntax error line 6 at position 119 unexpected 'then'.
parse error line 6 at position 166 near '<EOF>'.
syntax error line 6 at position 162 unexpected 'end'.
[2022-08-09 11:14:44,287] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=Stockdim_update, task_id=stg_2_tgt_merge_sd, execution_date=20220809T063646, start_date=20220809T151442, end_date=20220809T151444
[2022-08-09 11:14:44,364] {standard_task_runner.py:92} ERROR - Failed to execute job 216 for task stg_2_tgt_merge_sd (001003 (42000): 01a62cb2-0501-b543-006e-0a830001f12a: SQL compilation error:
syntax error line 6 at position 119 unexpected 'then'.
parse error line 6 at position 166 near '<EOF>'.
syntax error line 6 at position 162 unexpected 'end'.; 182333)
[2022-08-09 11:14:44,389] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-09 11:14:44,496] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
