[2022-08-11 22:04:28,283] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: nse_daily_data_load.Truncate_relaod_table scheduled__2022-08-10T13:37:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-08-11 22:04:28,283] {local_task_job.py:101} INFO - Task is not able to be run
[2022-08-11 22:23:40,810] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.Truncate_relaod_table scheduled__2022-08-10T13:37:00+00:00 [queued]>
[2022-08-11 22:23:40,832] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: nse_daily_data_load.Truncate_relaod_table scheduled__2022-08-10T13:37:00+00:00 [queued]>
[2022-08-11 22:23:40,860] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:23:40,861] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-08-11 22:23:40,861] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-11 22:23:40,933] {taskinstance.py:1377} INFO - Executing <Task(SnowflakeOperator): Truncate_relaod_table> on 2022-08-10 13:37:00+00:00
[2022-08-11 22:23:40,936] {standard_task_runner.py:52} INFO - Started process 12425 to run task
[2022-08-11 22:23:40,940] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'nse_daily_data_load', 'Truncate_relaod_table', 'scheduled__2022-08-10T13:37:00+00:00', '--job-id', '243', '--raw', '--subdir', 'DAGS_FOLDER/nse_daily_load_stg.py', '--cfg-path', '/tmp/tmpicoewih8', '--error-file', '/tmp/tmptnfut5r1']
[2022-08-11 22:23:40,941] {standard_task_runner.py:80} INFO - Job 243: Subtask Truncate_relaod_table
[2022-08-11 22:23:41,000] {task_command.py:369} INFO - Running <TaskInstance: nse_daily_data_load.Truncate_relaod_table scheduled__2022-08-10T13:37:00+00:00 [running]> on host osboxes
[2022-08-11 22:23:41,061] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=nse_daily_data_load
AIRFLOW_CTX_TASK_ID=Truncate_relaod_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-10T13:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-10T13:37:00+00:00
[2022-08-11 22:23:41,061] {snowflake.py:118} INFO - Executing:  call EDW_DEV.EDW.LOAD_NSE_DAILY_DATA_WITH_MEASURES(); 
[2022-08-11 22:23:41,067] {base.py:68} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2022-08-11 22:23:41,070] {connection.py:257} INFO - Snowflake Connector for Python Version: 2.7.8, Python Version: 3.8.10, Platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.29
[2022-08-11 22:23:41,070] {connection.py:876} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2022-08-11 22:23:41,070] {connection.py:894} INFO - Setting use_openssl_only mode to False
[2022-08-11 22:23:41,834] {cursor.py:710} INFO - query: [ALTER SESSION SET autocommit=True]
[2022-08-11 22:23:41,918] {cursor.py:734} INFO - query execution done
[2022-08-11 22:23:41,918] {snowflake.py:328} INFO - Running statement: call EDW_DEV.EDW.LOAD_NSE_DAILY_DATA_WITH_MEASURES();, parameters: None
[2022-08-11 22:23:41,918] {cursor.py:710} INFO - query: [call EDW_DEV.EDW.LOAD_NSE_DAILY_DATA_WITH_MEASURES();]
[2022-08-11 22:25:47,789] {cursor.py:734} INFO - query execution done
[2022-08-11 22:25:47,795] {snowflake.py:338} INFO - Statement execution info - {'LOAD_NSE_DAILY_DATA_WITH_MEASURES': 'ZYDUSLIFE'}
[2022-08-11 22:25:47,796] {snowflake.py:342} INFO - Rows affected: 1
[2022-08-11 22:25:47,796] {snowflake.py:343} INFO - Snowflake query id: 01a63a8f-0501-b64f-006e-0a830002403a
[2022-08-11 22:25:47,797] {connection.py:507} INFO - closed
[2022-08-11 22:25:47,866] {connection.py:510} INFO - No async queries seem to be running, deleting session
[2022-08-11 22:25:48,030] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=nse_daily_data_load, task_id=Truncate_relaod_table, execution_date=20220810T133700, start_date=20220812T022340, end_date=20220812T022548
[2022-08-11 22:25:48,140] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-11 22:25:48,200] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
